import React from 'react';
import { Table } from 'antd';
import {
  szhPassCount, mykPassCount, kkuPassCount, imlaPassCount,
  azuPassCount, ndogoPassCount, vituPassCount, utaPassCount,
  jum1PassCount, jum2PassCount, kut1PassCount, kut2PassCount,
  nzPassCount, mafPassCount, szhAverage, mykAverage, kkuAverage,
  imlaAverage, ndogoAverage, uanAverage, vituAverage, utaAverage,
  jum1Average, jum2Average, kut1Average, kut2Average, nzAverage,
  mafAverage,
} from './report/ReportFunctions';
import {
  Bar,
  BarChart,
  Legend,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { fetchRipotiYaShule } from '../api/ripoti';
import { useQuery } from 'react-query';



const data = [
  {
    "id": 1158,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "CHIUNGUTWA",
    "shuleNo": "EM.1826",
    "jina": "TWALIBU OMARI HUSSENI",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 12,
    "myk": 20,
    "szh": 32,
    "imla": 24,
    "uaf": 8,
    "picha": 16,
    "hzm": 20,
    "uta": 20,
    "maf": 4,
    "jum1": 8,
    "jum2": 8,
    "kut1": 16,
    "kut2": 8,
    "nz": 12,
    "kusT": 64,
    "kuaT": 68,
    "hesT": 76,
    "jumla": 208
  },
  {
    "id": 1256,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "ABDUKARIMU RAJABU  MOHAMEDI",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 16,
    "myk": 40,
    "szh": 36,
    "imla": 40,
    "uaf": 8,
    "picha": 24,
    "hzm": 20,
    "uta": 20,
    "maf": 16,
    "jum1": 8,
    "jum2": 8,
    "kut1": 8,
    "kut2": 8,
    "nz": 16,
    "kusT": 92,
    "kuaT": 92,
    "hesT": 84,
    "jumla": 268
  },
  {
    "id": 1257,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "AIZA  OLIVA  SAIMON",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 12,
    "myk": 40,
    "szh": 24,
    "imla": 40,
    "uaf": 14,
    "picha": 24,
    "hzm": 8,
    "uta": 12,
    "maf": 0,
    "jum1": 0,
    "jum2": 0,
    "kut1": 8,
    "kut2": 4,
    "nz": 12,
    "kusT": 76,
    "kuaT": 86,
    "hesT": 36,
    "jumla": 198
  },
  {
    "id": 1258,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "AKSHEI  RASHIDI  JUMA",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 4,
    "myk": 40,
    "szh": 36,
    "imla": 16,
    "uaf": 8,
    "picha": 24,
    "hzm": 16,
    "uta": 12,
    "maf": 4,
    "jum1": 8,
    "jum2": 0,
    "kut1": 8,
    "kut2": 4,
    "nz": 8,
    "kusT": 80,
    "kuaT": 64,
    "hesT": 44,
    "jumla": 188
  },
  {
    "id": 1259,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "AMIMU  ISSA ATHUMANI",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 16,
    "myk": 40,
    "szh": 36,
    "imla": 40,
    "uaf": 12,
    "picha": 24,
    "hzm": 20,
    "uta": 20,
    "maf": 16,
    "jum1": 8,
    "jum2": 12,
    "kut1": 8,
    "kut2": 12,
    "nz": 20,
    "kusT": 92,
    "kuaT": 96,
    "hesT": 96,
    "jumla": 284
  },
  {
    "id": 1260,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "AMLANI  NASORO  HAMISI",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 16,
    "myk": 40,
    "szh": 40,
    "imla": 24,
    "uaf": 8,
    "picha": 24,
    "hzm": 20,
    "uta": 20,
    "maf": 16,
    "jum1": 8,
    "jum2": 12,
    "kut1": 8,
    "kut2": 8,
    "nz": 20,
    "kusT": 96,
    "kuaT": 76,
    "hesT": 92,
    "jumla": 264
  },
  {
    "id": 1261,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "BRAYTON   CHEGE   LAZALO",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 0,
    "myk": 20,
    "szh": 20,
    "imla": 0,
    "uaf": 0,
    "picha": 0,
    "hzm": 0,
    "uta": 8,
    "maf": 4,
    "jum1": 8,
    "jum2": 0,
    "kut1": 4,
    "kut2": 4,
    "nz": 8,
    "kusT": 40,
    "kuaT": 0,
    "hesT": 36,
    "jumla": 76
  },
  {
    "id": 1262,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "DOGRAS LALANCE  SUWEDI",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 16,
    "myk": 40,
    "szh": 40,
    "imla": 40,
    "uaf": 8,
    "picha": 24,
    "hzm": 16,
    "uta": 20,
    "maf": 12,
    "jum1": 8,
    "jum2": 8,
    "kut1": 8,
    "kut2": 8,
    "nz": 16,
    "kusT": 96,
    "kuaT": 88,
    "hesT": 80,
    "jumla": 264
  },
  {
    "id": 1263,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "DOMONICK  PASCAR  MWAYA",
    "usajiliNo": null,
    "jinsia": "Mvulana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 16,
    "myk": 4,
    "szh": 16,
    "imla": 36,
    "uaf": 8,
    "picha": 20,
    "hzm": 8,
    "uta": 12,
    "maf": 12,
    "jum1": 8,
    "jum2": 4,
    "kut1": 4,
    "kut2": 8,
    "nz": 4,
    "kusT": 36,
    "kuaT": 72,
    "hesT": 52,
    "jumla": 160
  },
  {
    "id": 1264,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "FADGA  WAZIRI  YASINI",
    "usajiliNo": null,
    "jinsia": "Msichana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 20,
    "myk": 40,
    "szh": 36,
    "imla": 40,
    "uaf": 14,
    "picha": 24,
    "hzm": 16,
    "uta": 20,
    "maf": 4,
    "jum1": 8,
    "jum2": 0,
    "kut1": 8,
    "kut2": 4,
    "nz": 8,
    "kusT": 96,
    "kuaT": 94,
    "hesT": 52,
    "jumla": 242
  },
  {
    "id": 1265,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "FAKII  AMOSI  MTOLANJE",
    "usajiliNo": null,
    "jinsia": "Msichana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 12,
    "myk": 40,
    "szh": 36,
    "imla": 40,
    "uaf": 16,
    "picha": 24,
    "hzm": 20,
    "uta": 20,
    "maf": 16,
    "jum1": 8,
    "jum2": 0,
    "kut1": 8,
    "kut2": 8,
    "nz": 16,
    "kusT": 88,
    "kuaT": 100,
    "hesT": 76,
    "jumla": 264
  },
  {
    "id": 1266,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "FESTO  FEDRICK  MATHAYO",
    "usajiliNo": null,
    "jinsia": "Msichana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 8,
    "myk": 32,
    "szh": 28,
    "imla": 16,
    "uaf": 16,
    "picha": 24,
    "hzm": 6,
    "uta": 12,
    "maf": 4,
    "jum1": 8,
    "jum2": 0,
    "kut1": 4,
    "kut2": 0,
    "nz": 4,
    "kusT": 68,
    "kuaT": 62,
    "hesT": 32,
    "jumla": 162
  },
  {
    "id": 1266,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "FESTO  FEDRICK  MATHAYO",
    "usajiliNo": null,
    "jinsia": "Msichana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 8,
    "myk": 32,
    "szh": 28,
    "imla": 16,
    "uaf": 16,
    "picha": 24,
    "hzm": 6,
    "uta": 12,
    "maf": 4,
    "jum1": 8,
    "jum2": 0,
    "kut1": 4,
    "kut2": 0,
    "nz": 4,
    "kusT": 68,
    "kuaT": 62,
    "hesT": 32,
    "jumla": 162
  },
  {
    "id": 1266,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "FESTO  FEDRICK  MATHAYO",
    "usajiliNo": null,
    "jinsia": "Msichana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 8,
    "myk": 32,
    "szh": 28,
    "imla": 16,
    "uaf": 16,
    "picha": 24,
    "hzm": 6,
    "uta": 12,
    "maf": 4,
    "jum1": 8,
    "jum2": 0,
    "kut1": 4,
    "kut2": 0,
    "nz": 4,
    "kusT": 68,
    "kuaT": 62,
    "hesT": 32,
    "jumla": 162
  },
  {
    "id": 1266,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "FESTO  FEDRICK  MATHAYO",
    "usajiliNo": null,
    "jinsia": "Msichana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 8,
    "myk": 32,
    "szh": 28,
    "imla": 16,
    "uaf": 16,
    "picha": 24,
    "hzm": 6,
    "uta": 12,
    "maf": 4,
    "jum1": 8,
    "jum2": 0,
    "kut1": 4,
    "kut2": 0,
    "nz": 4,
    "kusT": 68,
    "kuaT": 62,
    "hesT": 32,
    "jumla": 162
  },
  {
    "id": 1266,
    "mkoa": null,
    "wilaya": "MASASI DC",
    "kata": "Chiungutwa",
    "shule": "LISANJE",
    "shuleNo": "EM.5141",
    "jina": "FESTO  FEDRICK  MATHAYO",
    "usajiliNo": null,
    "jinsia": "Msichana",
    "mwezi": "Novemba",
    "mwaka": 2022,
    "kku": 8,
    "myk": 32,
    "szh": 28,
    "imla": 16,
    "uaf": 16,
    "picha": 24,
    "hzm": 6,
    "uta": 12,
    "maf": 4,
    "jum1": 8,
    "jum2": 0,
    "kut1": 4,
    "kut2": 0,
    "nz": 4,
    "kusT": 68,
    "kuaT": 62,
    "hesT": 32,
    "jumla": 162
  },
  // Add more sample data as needed
];

const dataSource = [
  {
    area: 'Umahiri wa Kusoma'
  },
  {
    key: '1',
    area: 'Sauti za Herufi',
    description: 'Wanafunzi walioeza kutaja sauti za herufi',
    vizuriSanaWav: szhPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: szhPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: szhPassCount(data, "Mvulana", "VS") + szhPassCount(data, "Msichana", "VS"),
    vizuriWav: szhPassCount(data, "Mvulana", "VZ"),
    vizuriWas: szhPassCount(data, "Msichana", "VZ"),
    vizuriJum: szhPassCount(data, "Mvulana", "VZ") + szhPassCount(data, "Msichana", "VZ"),
    wastaniWav: szhPassCount(data, "Mvulana", "WS"),
    wastaniWas: szhPassCount(data, "Msichana", "WS"),
    wastaniJum: szhPassCount(data, "Mvulana", "WS") + szhPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: szhPassCount(data, "Mvulana", "DH"),
    dhaifuWas: szhPassCount(data, "Msichana", "DH"),
    dhaifuJum: szhPassCount(data, "Mvulana", "DH") + szhPassCount(data, "Msichana", "DH"),
    hajuiWav: szhPassCount(data, "Mvulana", "HJ"),
    hajuiWas: szhPassCount(data, "Msichana", "HJ"),
    hajuiJum: szhPassCount(data, "Mvulana", "HJ") + szhPassCount(data, "Msichana", "HJ"),
  },
  {
    key: '2',
    area: 'Maneno ya kubuni',
    description: 'Wanafunzi walioeza kusoma maneno ya kubuni',
    vizuriSanaWav: mykPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: mykPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: mykPassCount(data, "Mvulana", "VS") + mykPassCount(data, "Msichana", "VS"),
    vizuriWav: mykPassCount(data, "Mvulana", "VZ"),
    vizuriWas: mykPassCount(data, "Msichana", "VZ"),
    vizuriJum: mykPassCount(data, "Mvulana", "VZ") + mykPassCount(data, "Msichana", "VZ"),
    wastaniWav: mykPassCount(data, "Mvulana", "WS"),
    wastaniWas: mykPassCount(data, "Msichana", "WS"),
    wastaniJum: mykPassCount(data, "Mvulana", "WS") + mykPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: mykPassCount(data, "Mvulana", "DH"),
    dhaifuWas: mykPassCount(data, "Msichana", "DH"),
    dhaifuJum: mykPassCount(data, "Mvulana", "DH") + mykPassCount(data, "Msichana", "DH"),
    hajuiWav: mykPassCount(data, "Mvulana", "HJ"),
    hajuiWas: mykPassCount(data, "Msichana", "HJ"),
    hajuiJum: mykPassCount(data, "Mvulana", "HJ") + mykPassCount(data, "Msichana", "HJ"),
  },
  {
    key: '3',
    area: 'Kusoma kwa ufahamu',
    description: 'Wanafunzi walioeza kujibu kwa usahihi yanayotokana na kusoma kwa ufahamu',
    vizuriSanaWav: mykPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: mykPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: mykPassCount(data, "Mvulana", "VS") + mykPassCount(data, "Msichana", "VS"),
    vizuriWav: mykPassCount(data, "Mvulana", "VZ"),
    vizuriWas: mykPassCount(data, "Msichana", "VZ"),
    vizuriJum: mykPassCount(data, "Mvulana", "VZ") + mykPassCount(data, "Msichana", "VZ"),
    wastaniWav: mykPassCount(data, "Mvulana", "WS"),
    wastaniWas: mykPassCount(data, "Msichana", "WS"),
    wastaniJum: mykPassCount(data, "Mvulana", "WS") + mykPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: mykPassCount(data, "Mvulana", "DH"),
    dhaifuWas: mykPassCount(data, "Msichana", "DH"),
    dhaifuJum: mykPassCount(data, "Mvulana", "DH") + mykPassCount(data, "Msichana", "DH"),
    hajuiWav: mykPassCount(data, "Mvulana", "HJ"),
    hajuiWas: mykPassCount(data, "Msichana", "HJ"),
    hajuiJum: mykPassCount(data, "Mvulana", "HJ") + mykPassCount(data, "Msichana", "HJ"),
  },
  {
    area: 'Umahiri wa Kuandika'
  },
  {
    key: '1',
    area: 'Imla',
    description: 'Wanafunzi walioweza kuandika kwa usahihi kwenye sentensi za Imla',
    vizuriSanaWav: imlaPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: imlaPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: imlaPassCount(data, "Mvulana", "VS") + imlaPassCount(data, "Msichana", "VS"),
    vizuriWav: imlaPassCount(data, "Mvulana", "VZ"),
    vizuriWas: imlaPassCount(data, "Msichana", "VZ"),
    vizuriJum: imlaPassCount(data, "Mvulana", "VZ") + imlaPassCount(data, "Msichana", "VZ"),
    wastaniWav: imlaPassCount(data, "Mvulana", "WS"),
    wastaniWas: imlaPassCount(data, "Msichana", "WS"),
    wastaniJum: imlaPassCount(data, "Mvulana", "WS") + imlaPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: imlaPassCount(data, "Mvulana", "DH"),
    dhaifuWas: imlaPassCount(data, "Msichana", "DH"),
    dhaifuJum: imlaPassCount(data, "Mvulana", "DH") + imlaPassCount(data, "Msichana", "DH"),
    hajuiWav: imlaPassCount(data, "Mvulana", "HJ"),
    hajuiWas: imlaPassCount(data, "Msichana", "HJ"),
    hajuiJum: imlaPassCount(data, "Mvulana", "HJ") + imlaPassCount(data, "Msichana", "HJ"),
  },
  {
    key: '2',
    area: 'Kupigia mstari maneno yaliyoandikwa',
    description: 'Wwanafunzi walioweza kupigia mstari maneno yenye herufi kubwa au ndogo',
    vizuriSanaWav: ndogoPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: ndogoPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: ndogoPassCount(data, "Mvulana", "VS") + ndogoPassCount(data, "Msichana", "VS"),
    vizuriWav: ndogoPassCount(data, "Mvulana", "VZ"),
    vizuriWas: ndogoPassCount(data, "Msichana", "VZ"),
    vizuriJum: ndogoPassCount(data, "Mvulana", "VZ") + ndogoPassCount(data, "Msichana", "VZ"),
    wastaniWav: ndogoPassCount(data, "Mvulana", "WS"),
    wastaniWas: ndogoPassCount(data, "Msichana", "WS"),
    wastaniJum: ndogoPassCount(data, "Mvulana", "WS") + ndogoPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: ndogoPassCount(data, "Mvulana", "DH"),
    dhaifuWas: ndogoPassCount(data, "Msichana", "DH"),
    dhaifuJum: ndogoPassCount(data, "Mvulana", "DH") + ndogoPassCount(data, "Msichana", "DH"),
    hajuiWav: ndogoPassCount(data, "Mvulana", "HJ"),
    hajuiWas: ndogoPassCount(data, "Msichana", "HJ"),
    hajuiJum: ndogoPassCount(data, "Mvulana", "HJ") + ndogoPassCount(data, "Msichana", "HJ"),
  },
  {
    key: '3',
    area: 'Alama za Uandishi',
    description: 'Wanafunzi walioweza kuweka kwa usahihi alama za uandishi',
    vizuriSanaWav: azuPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: azuPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: azuPassCount(data, "Mvulana", "VS") + azuPassCount(data, "Msichana", "VS"),
    vizuriWav: azuPassCount(data, "Mvulana", "VZ"),
    vizuriWas: azuPassCount(data, "Msichana", "VZ"),
    vizuriJum: azuPassCount(data, "Mvulana", "VZ") + azuPassCount(data, "Msichana", "VZ"),
    wastaniWav: azuPassCount(data, "Mvulana", "WS"),
    wastaniWas: azuPassCount(data, "Msichana", "WS"),
    wastaniJum: azuPassCount(data, "Mvulana", "WS") + azuPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: azuPassCount(data, "Mvulana", "DH"),
    dhaifuWas: azuPassCount(data, "Msichana", "DH"),
    dhaifuJum: azuPassCount(data, "Mvulana", "DH") + azuPassCount(data, "Msichana", "DH"),
    hajuiWav: azuPassCount(data, "Mvulana", "HJ"),
    hajuiWas: azuPassCount(data, "Msichana", "HJ"),
    hajuiJum: azuPassCount(data, "Mvulana", "HJ") + azuPassCount(data, "Msichana", "HJ"),
  },
  {
    key: '4',
    area: 'Kutambua majina ya vitu',
    description: 'wanafunzi walioweza kuandika majina ya vitu kwa usahihi',
    vizuriSanaWav: vituPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: vituPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: vituPassCount(data, "Mvulana", "VS") + vituPassCount(data, "Msichana", "VS"),
    vizuriWav: vituPassCount(data, "Mvulana", "VZ"),
    vizuriWas: vituPassCount(data, "Msichana", "VZ"),
    vizuriJum: vituPassCount(data, "Mvulana", "VZ") + vituPassCount(data, "Msichana", "VZ"),
    wastaniWav: vituPassCount(data, "Mvulana", "WS"),
    wastaniWas: vituPassCount(data, "Msichana", "WS"),
    wastaniJum: vituPassCount(data, "Mvulana", "WS") + vituPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: vituPassCount(data, "Mvulana", "DH"),
    dhaifuWas: vituPassCount(data, "Msichana", "DH"),
    dhaifuJum: vituPassCount(data, "Mvulana", "DH") + vituPassCount(data, "Msichana", "DH"),
    hajuiWav: vituPassCount(data, "Mvulana", "HJ"),
    hajuiWas: vituPassCount(data, "Msichana", "HJ"),
    hajuiJum: vituPassCount(data, "Mvulana", "HJ") + vituPassCount(data, "Msichana", "HJ"),
  },
  {
    area: 'Umahiri wa Kuhesabu'
  },
  {
    key: '1',
    area: 'Utambuzi wa namba',
    description: 'Wanafunzi walioweza kutambua namba kwa usahihi',
    vizuriSanaWav: utaPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: utaPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: utaPassCount(data, "Mvulana", "VS") + utaPassCount(data, "Msichana", "VS"),
    vizuriWav: utaPassCount(data, "Mvulana", "VZ"),
    vizuriWas: utaPassCount(data, "Msichana", "VZ"),
    vizuriJum: utaPassCount(data, "Mvulana", "VZ") + utaPassCount(data, "Msichana", "VZ"),
    wastaniWav: utaPassCount(data, "Mvulana", "WS"),
    wastaniWas: utaPassCount(data, "Msichana", "WS"),
    wastaniJum: utaPassCount(data, "Mvulana", "WS") + utaPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: utaPassCount(data, "Mvulana", "DH"),
    dhaifuWas: utaPassCount(data, "Msichana", "DH"),
    dhaifuJum: utaPassCount(data, "Mvulana", "DH") + utaPassCount(data, "Msichana", "DH"),
    hajuiWav: utaPassCount(data, "Mvulana", "HJ"),
    hajuiWas: utaPassCount(data, "Msichana", "HJ"),
    hajuiJum: utaPassCount(data, "Mvulana", "HJ") + utaPassCount(data, "Msichana", "HJ"),
  },
  {
    key: '2',
    area: 'Namba Inayokosekana',
    description: 'Wanafunzi walioweza kujaza namba zinazokosekana kwa usahihi',
    vizuriSanaWav: nzPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: nzPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: nzPassCount(data, "Mvulana", "VS") + nzPassCount(data, "Msichana", "VS"),
    vizuriWav: nzPassCount(data, "Mvulana", "VZ"),
    vizuriWas: utaPassCount(data, "Msichana", "VZ"),
    vizuriJum: nzPassCount(data, "Mvulana", "VZ") + nzPassCount(data, "Msichana", "VZ"),
    wastaniWav: nzPassCount(data, "Mvulana", "WS"),
    wastaniWas: utaPassCount(data, "Msichana", "WS"),
    wastaniJum: nzPassCount(data, "Mvulana", "WS") + nzPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: nzPassCount(data, "Mvulana", "DH"),
    dhaifuWas: nzPassCount(data, "Msichana", "DH"),
    dhaifuJum: nzPassCount(data, "Mvulana", "DH") + nzPassCount(data, "Msichana", "DH"),
    hajuiWav: nzPassCount(data, "Mvulana", "HJ"),
    hajuiWas: utaPassCount(data, "Msichana", "HJ"),
    hajuiJum: nzPassCount(data, "Mvulana", "HJ") + nzPassCount(data, "Msichana", "HJ"),
  },
  {
    key: '3',
    area: 'Mafumbo',
    description: 'Wanafunzi walioweza kufumbua mafumbo kwa usahihi',
    vizuriSanaWav: mafPassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: mafPassCount(data, "Msichana", "VS"),
    vizuriSanaJum: mafPassCount(data, "Mvulana", "VS") + mafPassCount(data, "Msichana", "VS"),
    vizuriWav: mafPassCount(data, "Mvulana", "VZ"),
    vizuriWas: mafPassCount(data, "Msichana", "VZ"),
    vizuriJum: mafPassCount(data, "Mvulana", "VZ") + mafPassCount(data, "Msichana", "VZ"),
    wastaniWav: mafPassCount(data, "Mvulana", "WS"),
    wastaniWas: mafPassCount(data, "Msichana", "WS"),
    wastaniJum: mafPassCount(data, "Mvulana", "WS") + mafPassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: mafPassCount(data, "Mvulana", "DH"),
    dhaifuWas: mafPassCount(data, "Msichana", "DH"),
    dhaifuJum: mafPassCount(data, "Mvulana", "DH") + mafPassCount(data, "Msichana", "DH"),
    hajuiWav: utaPassCount(data, "Mvulana", "HJ"),
    hajuiWas: mafPassCount(data, "Msichana", "HJ"),
    hajuiJum: mafPassCount(data, "Mvulana", "HJ") + mafPassCount(data, "Msichana", "HJ"),
  },
  {
    area: '4. Matendo katika namba'
  },
  {
    key: '4(a)',
    area: 'Kujumlisha Ngazi ya I',
    description: 'Wanafunzi walioweza Kujumlisha namba ngazi ya I kwa usahihi',
    vizuriSanaWav: jum1PassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: jum1PassCount(data, "Msichana", "VS"),
    vizuriSanaJum: jum1PassCount(data, "Mvulana", "VS") + jum1PassCount(data, "Msichana", "VS"),
    vizuriWav: jum1PassCount(data, "Mvulana", "VZ"),
    vizuriWas: jum1PassCount(data, "Msichana", "VZ"),
    vizuriJum: jum1PassCount(data, "Mvulana", "VZ") + jum1PassCount(data, "Msichana", "VZ"),
    wastaniWav: jum1PassCount(data, "Mvulana", "WS"),
    wastaniWas: jum1PassCount(data, "Msichana", "WS"),
    wastaniJum: jum1PassCount(data, "Mvulana", "WS") + jum1PassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: jum1PassCount(data, "Mvulana", "DH"),
    dhaifuWas: jum1PassCount(data, "Msichana", "DH"),
    dhaifuJum: jum1PassCount(data, "Mvulana", "DH") + jum1PassCount(data, "Msichana", "DH"),
    hajuiWav: jum1PassCount(data, "Mvulana", "HJ"),
    hajuiWas: jum1PassCount(data, "Msichana", "HJ"),
    hajuiJum: jum1PassCount(data, "Mvulana", "HJ") + jum1PassCount(data, "Msichana", "HJ"),
  },
  {
    key: '4(b)',
    area: 'Kujumlisha Ngazi ya II',
    description: 'Wanafunzi walioweza Kujumlisha namba ngazi ya II kwa usahihi',
    vizuriSanaWav: jum2PassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: jum2PassCount(data, "Msichana", "VS"),
    vizuriSanaJum: jum2PassCount(data, "Mvulana", "VS") + jum2PassCount(data, "Msichana", "VS"),
    vizuriWav: jum2PassCount(data, "Mvulana", "VZ"),
    vizuriWas: jum2PassCount(data, "Msichana", "VZ"),
    vizuriJum: jum2PassCount(data, "Mvulana", "VZ") + jum2PassCount(data, "Msichana", "VZ"),
    wastaniWav: jum2PassCount(data, "Mvulana", "WS"),
    wastaniWas: jum2PassCount(data, "Msichana", "WS"),
    wastaniJum: jum2PassCount(data, "Mvulana", "WS") + jum2PassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: jum2PassCount(data, "Mvulana", "DH"),
    dhaifuWas: jum2PassCount(data, "Msichana", "DH"),
    dhaifuJum: jum2PassCount(data, "Mvulana", "DH") + jum2PassCount(data, "Msichana", "DH"),
    hajuiWav: jum2PassCount(data, "Mvulana", "HJ"),
    hajuiWas: jum2PassCount(data, "Msichana", "HJ"),
    hajuiJum: jum2PassCount(data, "Mvulana", "HJ") + jum2PassCount(data, "Msichana", "HJ"),
  },
  {
    key: '4(c)',
    area: 'Kutoa Ngazi ya I',
    description: 'Wanafunzi walioweza Kutoa namba ngazi ya I kwa usahihi',
    vizuriSanaWav: kut1PassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: kut1PassCount(data, "Msichana", "VS"),
    vizuriSanaJum: kut1PassCount(data, "Mvulana", "VS") + kut1PassCount(data, "Msichana", "VS"),
    vizuriWav: kut1PassCount(data, "Mvulana", "VZ"),
    vizuriWas: kut1PassCount(data, "Msichana", "VZ"),
    vizuriJum: kut1PassCount(data, "Mvulana", "VZ") + kut1PassCount(data, "Msichana", "VZ"),
    wastaniWav: kut1PassCount(data, "Mvulana", "WS"),
    wastaniWas: kut1PassCount(data, "Msichana", "WS"),
    wastaniJum: kut1PassCount(data, "Mvulana", "WS") + kut1PassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: kut1PassCount(data, "Mvulana", "DH"),
    dhaifuWas: kut1PassCount(data, "Msichana", "DH"),
    dhaifuJum: kut1PassCount(data, "Mvulana", "DH") + kut1PassCount(data, "Msichana", "DH"),
    hajuiWav: kut1PassCount(data, "Mvulana", "HJ"),
    hajuiWas: kut1PassCount(data, "Msichana", "HJ"),
    hajuiJum: kut1PassCount(data, "Mvulana", "HJ") + kut1PassCount(data, "Msichana", "HJ"),
  },
  {
    key: '4(d)',
    area: 'Kutoa Ngazi ya II',
    description: 'Wanafunzi walioweza Kutoa namba ngazi ya II kwa usahihi',
    vizuriSanaWav: kut2PassCount(data, "Mvulana", "VS"),
    vizuriSanaWas: kut2PassCount(data, "Msichana", "VS"),
    vizuriSanaJum: kut2PassCount(data, "Mvulana", "VS") + kut2PassCount(data, "Msichana", "VS"),
    vizuriWav: kut2PassCount(data, "Mvulana", "VZ"),
    vizuriWas: kut2PassCount(data, "Msichana", "VZ"),
    vizuriJum: kut2PassCount(data, "Mvulana", "VZ") + kut2PassCount(data, "Msichana", "VZ"),
    wastaniWav: kut2PassCount(data, "Mvulana", "WS"),
    wastaniWas: kut2PassCount(data, "Msichana", "WS"),
    wastaniJum: kut2PassCount(data, "Mvulana", "WS") + kut2PassCount(data, "Msichana", "Wastani/Inarishisha"),
    dhaifuWav: kut2PassCount(data, "Mvulana", "DH"),
    dhaifuWas: kut2PassCount(data, "Msichana", "DH"),
    dhaifuJum: kut2PassCount(data, "Mvulana", "DH") + kut2PassCount(data, "Msichana", "DH"),
    hajuiWav: kut2PassCount(data, "Mvulana", "HJ"),
    hajuiWas: kut2PassCount(data, "Msichana", "HJ"),
    hajuiJum: kut2PassCount(data, "Mvulana", "HJ") + kut2PassCount(data, "Msichana", "HJ"),
  },
];

const columns = [
  {
    title: 'sn',
    dataIndex: 'key',
    key: 'key',
  },
  {
    title: 'Eneo Linalopimwa',
    dataIndex: 'area',
    key: 'area',
  },
  {
    title: 'Kiwango cha Ufanisi/ Ufaulu',
    dataIndex: 'description',
    key: 'description',
  },
  {
    title: 'Ufaulu',
    children: [
      {
        title: 'Vizuri Sana',
        children: [
          { title: 'Wav', dataIndex: 'vizuriSanaWav', key: 'vizuriSanaWav' },
          { title: 'Was', dataIndex: 'vizuriSanaWas', key: 'vizuriSanaWas' },
          { title: 'Jum', dataIndex: 'vizuriSanaJum', key: 'vizuriSanaJum' },
        ],
      },
      {
        title: 'Vizuri',
        children: [
          { title: 'Wav', dataIndex: 'vizuriWav', key: 'vizuriWav' },
          { title: 'Was', dataIndex: 'vizuriWas', key: 'vizuriWas' },
          { title: 'Jum', dataIndex: 'vizuriJum', key: 'vizuriJum' },
        ],
      },
      {
        title: 'Wastani',
        children: [
          { title: 'Wav', dataIndex: 'wastaniWav', key: 'wastaniWav' },
          { title: 'Was', dataIndex: 'wastaniWas', key: 'wastaniWas' },
          { title: 'Jum', dataIndex: 'wastaniJum', key: 'wastaniJum' },
        ],
      },
      {
        title: 'Dhaifu',
        children: [
          { title: 'Wav', dataIndex: 'dhaifuWav', key: 'dhaifuWav' },
          { title: 'Was', dataIndex: 'dhaifuWas', key: 'dhaifuWas' },
          { title: 'Jum', dataIndex: 'dhaifuJum', key: 'dhaifuJum' },
        ],
      },
      {
        title: 'Hajui',
        children: [
          { title: 'Wav', dataIndex: 'hajuiWav', key: 'hajuiWav' },
          { title: 'Was', dataIndex: 'hajuiWas', key: 'hajuiWas' },
          { title: 'Jum', dataIndex: 'hajuiJum', key: 'hajuiJum' },
        ],
      },
    ],
  },
];

const averageData = [
  {
    Eneo: "SZH",
    Wastani: szhAverage(data),
  },

  {
    Eneo: "MYK",
    Wastani: mykAverage(data),
  },

  {
    Eneo: "KKU",
    Wastani: kkuAverage(data),
  },

  {
    Eneo: "Imla",
    Wastani: imlaAverage(data),
  },

  {
    Eneo: "KMMY",
    Wastani: ndogoAverage(data),
  },

  {
    Eneo: "AZU",
    Wastani: uanAverage(data),
  },

  {
    Eneo: "Vitu",
    Wastani: vituAverage(data),
  },

  {
    Eneo: "UTA",
    Wastani: utaAverage(data),
  },

  {
    Eneo: "JUMI",
    Wastani: jum1Average(data),
  },

  {
    Eneo: "JUMII",
    Wastani: jum2Average(data),
  },

  {
    Eneo: "KUTI",
    Wastani: kut1Average(data),
  },

  {
    Eneo: "KUTII",
    Wastani: kut2Average(data),
  },

  {
    Eneo: "NZ",
    Wastani: nzAverage(data),
  },

  {
    Eneo: "Mafumbo",
    Wastani: mafAverage(data),
  },
];

const SubTaskAverage = () => (
  <div className="container">
    <h4>Wastani wa kila Ukarasa</h4>

    <ResponsiveContainer width="100%" height={600}>
      <BarChart
        cx={"50%"}
        data={averageData}
        margin={{ top: 10, bottom: 10, left: 30, right: 30 }}
      >
        <XAxis dataKey={"Eneo"} />
        <YAxis />
        <Tooltip />
        <Legend />
        <Bar dataKey={"Wastani"} fill={COLORS[1]} />
      </BarChart>
    </ResponsiveContainer>
  </div>
);

const COLORS = [
  "#43BF2A",
  "#BFB82A",
  "#2A80BF",
  "#722ABF",
  "#BF2AA6",
  "#BA2ABF",
  "#D97B2D",
  "#D9322D",
  "#05118C",
];

const App = () => (
  <>
    <Table
      dataSource={dataSource}
      columns={columns}
      pagination={false}
      className='custom-table mb-5'
    />
    <SubTaskAverage />
  </>
);

export default App;

